# Generated by Django 3.2.1 on 2021-05-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('bio', models.TextField()),
                ('imagePath', models.FilePathField(verbose_name='./imgs')),
                ('phoneNumber', models.CharField(max_length=20)),
            ],
        ),
    ]
