# Generated by Django 3.2.1 on 2021-05-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210504_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='imagePath',
            field=models.FilePathField(null=True, verbose_name='/home/vuk/Documents/imgs'),
        ),
    ]
