# Generated by Django 3.2.1 on 2021-05-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_imagepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='imagePath',
        ),
        migrations.AddField(
            model_name='user',
            name='imageName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
