# Generated by Django 3.2.3 on 2021-05-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210504_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
