# Generated by Django 3.2.3 on 2021-05-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210518_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='desc',
            new_name='description',
        ),
    ]
