# Generated by Django 3.2.3 on 2021-05-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210518_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='isClosed',
            field=models.BooleanField(default=False),
        ),
    ]
