# Generated by Django 3.2.3 on 2021-05-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ad_isclosed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='postTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
