# Generated by Django 3.2.3 on 2021-05-22 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_rating_posttime'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='comment_pk',
        ),
    ]
