# Generated by Django 3.2.3 on 2021-05-26 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210522_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.ManyToManyField(through='api.Earned', to='api.Badge'),
        ),
        migrations.AlterField(
            model_name='earned',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.badge'),
        ),
        migrations.AlterField(
            model_name='earned',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
