# Generated by Django 3.2.3 on 2021-05-27 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210526_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='tags',
            field=models.ManyToManyField(through='api.RelatedTo', to='api.Tag'),
        ),
        migrations.AlterField(
            model_name='relatedto',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ad'),
        ),
        migrations.AlterField(
            model_name='relatedto',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag'),
        ),
    ]
