# Generated by Django 3.2.3 on 2021-06-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210527_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='qbChatId',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='userQbId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
