# Generated by Django 3.2.3 on 2021-06-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210621_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfcm',
            name='fcmToken',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
