# Generated by Django 3.2.3 on 2021-06-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_userfcm_fcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tagged',
            field=models.BooleanField(null=True),
        ),
    ]
